version: "3.9"

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    container_name: ecommerce_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ..:/app
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    depends_on:
      - db
      - redis

  db:
    image: postgres:14
    container_name: ecommerce_db
    restart: always
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: ecommerce_user
      POSTGRES_PASSWORD: ecommerce_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: ecommerce_redis

volumes:
  postgres_data:
