# Generated by Django 5.2.4 on 2025-08-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['user'], name='authenticat_user_id_966a9a_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['role'], name='authenticat_role_id_d5d365_idx'),
        ),
    ]
